# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml .
COPY src ./src
COPY README.md LICENSE .

RUN pip install --no-cache-dir .

ENTRYPOINT ["ip-acquirer"]
